"""
Settings for the FastAPI project template.
This module contains the default settings and configurations for the FastAPI project template.
generated by FastAPIBig.
"""
from pydantic_settings import BaseSettings, SettingsConfigDict
from pathlib import Path
import sys

# Base directory for SQLite storage
BASE_DIR = Path(__file__).resolve().parent.parent

# add BASE_DIR root to sys path
sys.path.append(str(BASE_DIR.parent.parent))



class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")
    # SECURITY WARNING: keep the secret key used in production secret!
    ALLOWED_HOSTS: list[str] = ["*"]
    # Default to SQLite if the user doesn't configure a database
    DATABASE_URL: str = f"sqlite+aiosqlite:///{BASE_DIR}/db.sqlite3"


    API_JWT_SECRET: str
    API_JWT_ALGORITHM: str
    SECRET_KEY: str

    DEBUG: bool = True


settings = Settings()
